import os
from typing import Optional
from mcp.server.fastmcp import FastMCP
from fastapi import FastAPI
from youtube_transcript_api import YouTubeTranscriptApi

mcp = FastMCP("youtube_transcriptor")
app = FastAPI()


@mcp.tool()
def transcribe_video(video: str, config: dict = None) -> str:
    video_id = video.replace("https://www.youtube.com/watch?v=", "").replace("https://youtu.be/", "").strip()
    if not YouTubeTranscriptApi:
        raise ImportError("youtube-transcript-api is not installed.")
    # Get all available transcripts for the video
    transcripts = YouTubeTranscriptApi.list_transcripts(video_id)
    # Try to get the first available transcript (manual or autogenerated)
    transcript = None
    for t in transcripts:
        try:
            transcript = t.fetch()
            break
        except Exception:
            continue
    if not transcript:
        return None
    return '\n'.join([x.text for x in transcript])


if __name__ == "__main__":    
    mcp.run()